mi_lista=['a','b','c']
mi_lista2=['d','e','f']
resultado=len(mi_lista)
r1=mi_lista[0:1]
mi_lista3=mi_lista+mi_lista2
mi_lista3[3]='L'
mi_lista3.append('G')
mi_lista3.pop(0)
lista=['g','o','l','a']
lista.sort()
lista.reverse()
print(lista)
print(mi_lista3)
print(resultado)
print(r1)
print(mi_lista+mi_lista2)
